### PR TITLE
feat(inference): add support for custom resamplers in particle filtering

### PR DESCRIPTION
**Pull request by chentoast**
The current PF implementation uses multinomial resampling, which is not really ideal. Add support for custom resampling algorithms like systematic or residual sampling in `maybe_resample!`.

Side note: is there a reason why we save `state.parents` and `state.new_trace`, instead of just assigning them as local variables? I don't really see them used anywhere else.

### CODE REVIEW

**Comment by femtomc** [comment]
Hi @chentau -- we actually have a package for this: https://github.com/probcomp/GenParticleFilters.jl

which includes extended forms of resampling.

Feel free to add a PR there, if there is anything missing that you want to implement.

**Comment by chentoast** [comment]
Thanks for letting me know :)

**Comment by femtomc** [comment]
Re @chentau -- @ztangent may know better about `state.parents` and `state.new_traces`. It's true that you can allocate them as local variables in the implementation that you're describing.

One thing you can do is pre-allocate arrays for both when you instantiate `ParticleFilterState` -- which is often a good performance idiom. With the state carried throughout inference, the GC will avoid collecting these (e.g. if you don't explicitly write to stack allocate).

That's one reason I can see.

**Comment by ztangent** [comment]
Yes, I suspect avoiding GC might be an important reason! I actually continued using `state.parents` and `state.new_traces` in `GenParticleFilters` because that was what @marcoct was doing, and he may have more insight as to why.

Also, @chentau, glad to know that others are finding a use case for custom resampling methods! I hope the ones implement in GenParticleFilters are sufficient, and if not, feel free to make a PR there :)

**Pull request closed without merging**
