### PR TITLE
Bug fix in involution MCMC docs

### PR DESCRIPTION
**Pull request by georgematheos**
I may be misunderstanding this part--but I'm pretty sure in this warning, the issue is that the Jacobian could be zero, not that it could be nonzero!  @marcoct

### CODE REVIEW

**Comment by bzinberg** [comment]
nonzero -> zero LGTM.  I.m.o. the "and have zeros in every slot except one" makes it a little harder to understand, since the determinant would be zero even without that extra condition.

**Comment by georgematheos** [comment]
Isn't it possible that the determinant can be nonzero without that additional condition?  Eg. we could have the Jacobian
```
1 1 0
1 1 0
0 0 1
```
which does not have nonzero determinant even though it has 2 identical rows.

**Comment by bzinberg** [comment]
The determinant of any matrix that has two identical rows is zero.

**Comment by georgematheos** [comment]
Right, not sure what I was talking about (or where that "example" came from).  Will change the docs to just say that the determinant would be zero.

**Review by bzinberg — APPROVED** [review]

**Comment by marcoct** [comment]
Thanks George! I moved around a lot of the content on my working branch for the trace transform DSL changes, so I just added this change to my PR: https://github.com/probcomp/Gen.jl/pull/290

**Comment by marcoct** [comment]
Closing this, since it was incorporated into https://github.com/probcomp/Gen.jl/pull/290

**Pull request closed without merging**
